In [1]:
#if tf <2.0
from keras.preprocessing.text import one_hot

In [2]:
from tensorflow.keras.preprocessing.text import one_hot

In [3]:
sent=['the glass of milk',
      'the glass of juice',
      'the cup of tea',
      'I am a good boy',
      'I am a good developer',
      'understand the meaning of words',
      'your videos are good']

In [4]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [5]:
voc_size = 10000

In [6]:
one_hot_rep = [ one_hot(word, voc_size) for word in sent ]
print(one_hot_rep)

[[2535, 6937, 3394, 9395], [2535, 6937, 3394, 1503], [2535, 6110, 3394, 9168], [2162, 544, 912, 8051, 2875], [2162, 544, 912, 8051, 8864], [983, 2535, 6913, 3394, 7080], [6666, 115, 5401, 8051]]


In [7]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [8]:
import numpy as np
sent_length =8
embedded_docs= pad_sequences(one_hot_rep, padding='pre', maxlen= sent_length)
print(embedded_docs)

[[   0    0    0    0 2535 6937 3394 9395]
 [   0    0    0    0 2535 6937 3394 1503]
 [   0    0    0    0 2535 6110 3394 9168]
 [   0    0    0 2162  544  912 8051 2875]
 [   0    0    0 2162  544  912 8051 8864]
 [   0    0    0  983 2535 6913 3394 7080]
 [   0    0    0    0 6666  115 5401 8051]]


In [9]:
dim=15
model= Sequential()
model.add(Embedding(voc_size, 10, input_length= sent_length))
model.compile('adam', 'mse')
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, 8, 10)             100000    
Total params: 100,000
Trainable params: 100,000
Non-trainable params: 0
_________________________________________________________________


In [10]:
print(model.predict(embedded_docs))

[[[ 1.85333192e-04  3.63030694e-02  2.63955444e-03  3.82110216e-02
   -2.59254929e-02  4.17500474e-02 -1.26117468e-02  4.88970391e-02
   -4.63647023e-02 -4.55754884e-02]
  [ 1.85333192e-04  3.63030694e-02  2.63955444e-03  3.82110216e-02
   -2.59254929e-02  4.17500474e-02 -1.26117468e-02  4.88970391e-02
   -4.63647023e-02 -4.55754884e-02]
  [ 1.85333192e-04  3.63030694e-02  2.63955444e-03  3.82110216e-02
   -2.59254929e-02  4.17500474e-02 -1.26117468e-02  4.88970391e-02
   -4.63647023e-02 -4.55754884e-02]
  [ 1.85333192e-04  3.63030694e-02  2.63955444e-03  3.82110216e-02
   -2.59254929e-02  4.17500474e-02 -1.26117468e-02  4.88970391e-02
   -4.63647023e-02 -4.55754884e-02]
  [-2.98147444e-02  2.00651959e-03  2.14733966e-02  3.97671349e-02
    6.59452751e-03  2.40466334e-02 -1.95376277e-02 -4.36591171e-02
    3.70928310e-02 -2.48256922e-02]
  [ 2.28129514e-02 -4.79105227e-02 -2.51693372e-02  2.60871314e-02
   -4.45850864e-02  2.06960104e-02  1.33164860e-02  2.87003778e-02
    4.09345701e-

In [11]:
embedded_docs[0]

array([   0,    0,    0,    0, 2535, 6937, 3394, 9395], dtype=int32)

In [12]:
print(model.predict(embedded_docs[0]))

[[[ 0.00018533  0.03630307  0.00263955  0.03821102 -0.02592549
    0.04175005 -0.01261175  0.04889704 -0.0463647  -0.04557549]]

 [[ 0.00018533  0.03630307  0.00263955  0.03821102 -0.02592549
    0.04175005 -0.01261175  0.04889704 -0.0463647  -0.04557549]]

 [[ 0.00018533  0.03630307  0.00263955  0.03821102 -0.02592549
    0.04175005 -0.01261175  0.04889704 -0.0463647  -0.04557549]]

 [[ 0.00018533  0.03630307  0.00263955  0.03821102 -0.02592549
    0.04175005 -0.01261175  0.04889704 -0.0463647  -0.04557549]]

 [[-0.02981474  0.00200652  0.0214734   0.03976713  0.00659453
    0.02404663 -0.01953763 -0.04365912  0.03709283 -0.02482569]]

 [[ 0.02281295 -0.04791052 -0.02516934  0.02608713 -0.04458509
    0.02069601  0.01331649  0.02870038  0.00409346 -0.02045939]]

 [[ 0.00907434 -0.03032738 -0.03932054  0.00975932 -0.04308945
   -0.01144682 -0.01692991 -0.00990589 -0.00748638 -0.00279761]]

 [[ 0.04760504  0.03622494  0.01615912  0.003869   -0.04945204
   -0.01302977 -0.02549857 -0.0430